build: off
environment:

  matrix:
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-rtos"

platform:
  - x64

install:
- cmd: git submodule update --init --recursive
- cmd: SET PATH=C:\Python37-x64;C:\Python37-x64\Scripts;%PATH%
- cmd: pip3 install -U https://github.com/OS-Q/S03/archive/master.zip
- cmd: platformio platform install file://.

test_script:
- cmd: platformio run -d %PLATFORMIO_PROJECT_DIR%

